export const defaultVolunteers = [
  {
    id: 1,
    name: "Anita Sharma",
    age: 45,
    qualification: "B.Sc Nursing",
    skills: ['First Aid', 'Elder Care'],
    profileImage: "/images/vol1.jpg",
    bio: "Experienced caregiver with 10+ years of service in elderly support.",
    location: "Delhi", // New location field
    phone: "8831401210",
    email: "anita.sharma@example.com",
  },
  {
    id: 2,
    name: "Rahul Verma",
    age: 30,
    qualification: "B.Tech IT",
    skills: ['Tech Help', 'Social Media Guidance'],
    profileImage: "/images/vol2.jpg",
    bio: "Tech-savvy volunteer who helps elders go digital.",
    location: "Mumbai", // New location field
    phone: "6369144025",
    email: "rahul.verma@example.com",
  },
  {
    id: 3,
    name: "Priya Nair",
    age: 35,
    qualification: "M.A Psychology",
    skills: ['Counseling', 'Companionship'],
    profileImage: "/images/vol3.jpg",
    bio: "Professional counselor providing emotional support to elders.",
    location: "Bangalore", // New location field
    phone: "7375902675",
    email: "priya.nair@example.com",
  },
  {
    id: 4,
    name: "Amit Joshi",
    age: 28,
    qualification: "Fitness Trainer",
    skills: ['Yoga', 'Light Workouts'],
    profileImage: "/images/vol4.jpg",
    bio: "Passionate about wellness and senior fitness programs.",
    location: "Chennai", // New location field
    phone: "9845301043",
    email: "amit.joshi@example.com",
  },
  {
    id: 5,
    name: "Meera Iyer",
    age: 42,
    qualification: "Social Worker",
    skills: ['Daily Wellness', 'Check-ins'],
    profileImage: "/images/vol5.jpg",
    bio: "Empathetic volunteer offering companionship and support.",
    location: "Kolkata", // New location field
    phone: "9380135676",
    email: "meera.iyer@example.com",
  },
  {
    id: 6,
    name: "Ravi Kumar",
    age: 34,
    qualification: "MBA",
    skills: ['Errands', 'Financial Guidance'],
    profileImage: "/images/vol6.jpg",
    bio: "Helps with banking, bill payments, and errands.",
    location: "Delhi", // New location field
    phone: "9083243529",
    email: "ravi.kumar@example.com",
  },
  {
    id: 7,
    name: "Sonal Gupta",
    age: 29,
    qualification: "Dietician",
    skills: ['Nutrition', 'Grocery Help'],
    profileImage: "/images/vol7.jpg",
    bio: "Provides nutrition tips and shopping support.",
    location: "Mumbai", // New location field
    phone: "7689602332",
    email: "sonal.gupta@example.com",
  },
  {
    id: 8,
    name: "Manoj Singh",
    age: 36,
    qualification: "IT Consultant",
    skills: ['Smartphone Setup', 'Online Services'],
    profileImage: "/images/vol8.jpg",
    bio: "Guides elderly people through technology usage.",
    location: "Bangalore", // New location field
    phone: "7598333717",
    email: "manoj.singh@example.com",
  },
  {
    id: 9,
    name: "Nandini Rao",
    age: 40,
    qualification: "B.A Literature",
    skills: ['Reading', 'Companionship'],
    profileImage: "/images/vol9.jpg",
    bio: "Spends time reading and storytelling with elders.",
    location: "Chennai", // New location field
    phone: "9092131660",
    email: "nandini.rao@example.com",
  },
  {
    id: 10,
    name: "Karan Mehta",
    age: 32,
    qualification: "Logistics Coordinator",
    skills: ['Parcel Delivery', 'Medicine Pickup'],
    profileImage: "/images/vol10.jpg",
    bio: "Manages logistics support for daily tasks.",
    location: "Kolkata", // New location field
    phone: "9751511717",
    email: "karan.mehta@example.com",
  },
  {
    id: 11,
    name: "Simran Kaur",
    age: 27,
    qualification: "B.Sc Psychology",
    skills: ['Counseling', 'Mental Health'],
    profileImage: "/images/vol11.jpg",
    bio: "Specializes in improving elder mental health.",
    location: "Delhi", // New location field
    phone: "8838301447",
    email: "simran.kaur@example.com",
  },
  {
    id: 12,
    name: "Deepak Jain",
    age: 38,
    qualification: "Retail Assistant",
    skills: ['Grocery Shopping', 'Payment Help'],
    profileImage: "/images/vol12.jpg",
    bio: "Supports grocery runs and elder shopping needs.",
    location: "Mumbai", // New location field
    phone: "6810432790",
    email: "deepak.jain@example.com",
  },
  {
    id: 13,
    name: "Lakshmi Menon",
    age: 33,
    qualification: "Physiotherapist",
    skills: ['Stretching', 'Pain Relief'],
    profileImage: "/images/vol13.jpg",
    bio: "Helps seniors recover and stay physically active.",
    location: "Bangalore", // New location field
    phone: "7967900240",
    email: "lakshmi.menon@example.com",
  },
  {
    id: 14,
    name: "Arjun Desai",
    age: 41,
    qualification: "Engineer",
    skills: ['Smart Home Setup', 'Safety Checks'],
    profileImage: "/images/vol14.jpg",
    bio: "Installs and configures smart home devices for safety.",
    location: "Chennai", // New location field
    phone: "8790988824",
    email: "arjun.desai@example.com",
  },
  {
    id: 15,
    name: "Pooja Reddy",
    age: 37,
    qualification: "Nutritionist",
    skills: ['Meal Planning', 'Grocery Help'],
    profileImage: "/images/vol15.jpg",
    bio: "Guides elders on healthy eating habits and diets.",
    location: "Kolkata", // New location field
    phone: "7071131290",
    email: "pooja.reddy@example.com",
  },
];
  
export default defaultVolunteers;
